apiVersion: v2
name: tfo-collector
description: TelemetryFlow Collector - OTLP gateway for traces, metrics, and logs
type: application
version: 0.1.0
appVersion: "1.1.7"
keywords:
  - observability
  - opentelemetry
  - otlp
  - collector
  - telemetry
home: https://telemetryflow.io
sources:
  - https://github.com/telemetryflow/telemetryflow-collector
maintainers:
  - name: TelemetryFlow Team
    email: support@telemetryflow.id
