// TelemetryFlow Collector - AI-Powered Observability & Incident Response Management (IRM) Platform
// Copyright (c) 2024-2026 Telemetri Data Indonesia. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package tfoidentityextension_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/extension/extensiontest"

	"github.com/telemetryflow/telemetryflow-collector/components/extension/tfoidentityextension"
)

// identityGetter mirrors the unexported IdentityProvider surface so external
// tests can drive the getters on the unexported extension type.
type identityGetter interface {
	GetCollectorID() string
	GetHostname() string
	GetName() string
	GetDescription() string
	GetTags() map[string]string
	ShouldEnrichResources() bool
}

func newStartedIdentityExtension(t *testing.T, cfg *tfoidentityextension.Config) component.Component {
	t.Helper()
	factory := tfoidentityextension.NewFactory()
	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))
	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)
	require.NoError(t, ext.Start(context.Background(), componenttest.NewNopHost()))
	t.Cleanup(func() { _ = ext.Shutdown(context.Background()) })
	return ext
}

func TestExtension_GetCollectorID_Configured(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	cfg.ID = "collector-prod-01"
	cfg.Hostname = "host-01"

	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok, "extension must satisfy identityGetter")

	assert.Equal(t, "collector-prod-01", g.GetCollectorID())
	assert.Equal(t, "host-01", g.GetHostname())
}

func TestExtension_GetCollectorID_AutoGenerated(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	// Leave ID empty — Start() should generate a UUID.
	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)

	id := g.GetCollectorID()
	assert.NotEmpty(t, id, "auto-generated collector ID must be non-empty")
	assert.Len(t, id, 36, "expected UUID-format length")
}

func TestExtension_GetHostname_AutoDetected(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	// Leave Hostname empty — Start() should call os.Hostname().
	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)
	assert.NotEmpty(t, g.GetHostname(), "auto-detected hostname must be non-empty")
}

func TestExtension_GetName_Description(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	cfg.Name = "My Collector"
	cfg.Description = "Test collector"

	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)
	assert.Equal(t, "My Collector", g.GetName())
	assert.Equal(t, "Test collector", g.GetDescription())
}

func TestExtension_GetTags(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	cfg.Tags = map[string]string{"env": "prod", "region": "us-east-1"}

	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)
	tags := g.GetTags()
	assert.Equal(t, "prod", tags["env"])
	assert.Equal(t, "us-east-1", tags["region"])
}

func TestExtension_ShouldEnrichResources_True(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	cfg.EnrichResources = true

	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)
	assert.True(t, g.ShouldEnrichResources())
}

func TestExtension_ShouldEnrichResources_False(t *testing.T) {
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	cfg.EnrichResources = false

	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)
	assert.False(t, g.ShouldEnrichResources())
}

func TestExtension_DefaultsPreserved(t *testing.T) {
	// Default config sets Name, Description, Tags, EnrichResources=true.
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	ext := newStartedIdentityExtension(t, cfg)
	g, ok := ext.(identityGetter)
	require.True(t, ok)
	assert.Equal(t, "TelemetryFlow Collector", g.GetName())
	assert.Contains(t, g.GetDescription(), "TelemetryFlow Collector")
	assert.NotNil(t, g.GetTags())
	assert.True(t, g.ShouldEnrichResources())
}

func TestExtension_DoubleStart(t *testing.T) {
	// Start() is idempotent at the extension level — calling Start twice should not panic.
	cfg := tfoidentityextension.NewFactory().CreateDefaultConfig().(*tfoidentityextension.Config)
	cfg.ID = "stable-id"
	cfg.Hostname = "stable-host"

	factory := tfoidentityextension.NewFactory()
	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))
	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)

	require.NoError(t, ext.Start(context.Background(), componenttest.NewNopHost()))
	require.NoError(t, ext.Start(context.Background(), componenttest.NewNopHost()))
	require.NoError(t, ext.Shutdown(context.Background()))
}
