// TelemetryFlow Collector - Community Enterprise Observability Platform (CEOP)
// Copyright (c) 2024-2026 TelemetryFlow. All rights reserved.

package tfoidentityextension_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/extension/extensiontest"

	"github.com/telemetryflow/telemetryflow-collector/components/extension/tfoidentityextension"
)

func TestNewFactory(t *testing.T) {
	factory := tfoidentityextension.NewFactory()

	assert.NotNil(t, factory)
	assert.Equal(t, component.MustNewType("tfoidentity"), factory.Type())
}

func TestCreateDefaultConfig(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	cfg := factory.CreateDefaultConfig()

	require.NotNil(t, cfg)
	assert.IsType(t, &tfoidentityextension.Config{}, cfg)

	oCfg := cfg.(*tfoidentityextension.Config)
	assert.Empty(t, oCfg.ID)
	assert.Empty(t, oCfg.Hostname)
	assert.Equal(t, "TelemetryFlow Collector", oCfg.Name)
	assert.Equal(t, "TelemetryFlow Collector - Community Enterprise Observability Platform", oCfg.Description)
	assert.True(t, oCfg.EnrichResources) // Default is true
}

func TestFactory_CreateExtension(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	cfg := factory.CreateDefaultConfig().(*tfoidentityextension.Config)

	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))

	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)
	require.NotNil(t, ext)
}

func TestExtension_Lifecycle(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	cfg := factory.CreateDefaultConfig().(*tfoidentityextension.Config)

	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))

	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)

	// Test start
	err = ext.Start(context.Background(), componenttest.NewNopHost())
	require.NoError(t, err)

	// Test shutdown
	err = ext.Shutdown(context.Background())
	require.NoError(t, err)
}

func TestExtension_WithCustomID(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	cfg := factory.CreateDefaultConfig().(*tfoidentityextension.Config)

	cfg.ID = "custom-collector-id"
	cfg.Name = "My Custom Collector"
	cfg.Description = "A test collector"
	cfg.Tags = map[string]string{"env": "test"}

	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))

	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)

	err = ext.Start(context.Background(), componenttest.NewNopHost())
	require.NoError(t, err)

	// Test that extension was created successfully
	assert.NotNil(t, ext)

	err = ext.Shutdown(context.Background())
	require.NoError(t, err)
}

func TestExtension_AutoGeneratedID(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	cfg := factory.CreateDefaultConfig().(*tfoidentityextension.Config)

	// Don't set ID - should be auto-generated

	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))

	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)

	err = ext.Start(context.Background(), componenttest.NewNopHost())
	require.NoError(t, err)

	// Test that extension was created successfully
	assert.NotNil(t, ext)

	err = ext.Shutdown(context.Background())
	require.NoError(t, err)
}

func TestExtension_AutoDetectedHostname(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	cfg := factory.CreateDefaultConfig().(*tfoidentityextension.Config)

	// Don't set Hostname - should be auto-detected

	set := extensiontest.NewNopSettings(component.MustNewType("tfoidentity"))

	ext, err := factory.Create(context.Background(), set, cfg)
	require.NoError(t, err)

	err = ext.Start(context.Background(), componenttest.NewNopHost())
	require.NoError(t, err)

	// Test that extension was created successfully
	assert.NotNil(t, ext)

	err = ext.Shutdown(context.Background())
	require.NoError(t, err)
}

func TestFactory_StabilityLevel(t *testing.T) {
	factory := tfoidentityextension.NewFactory()
	assert.Equal(t, component.StabilityLevelStable, factory.Stability())
}

func TestFactory_TypeConstant(t *testing.T) {
	assert.Equal(t, "tfoidentity", tfoidentityextension.TypeStr)
}
