apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfo-collector.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tfo-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEMETRYFLOW_API_KEY_ID: {{ required "telemetryflow.apiKeyId is required" .Values.telemetryflow.apiKeyId | quote }}
  TELEMETRYFLOW_API_KEY_SECRET: {{ required "telemetryflow.apiKeySecret is required" .Values.telemetryflow.apiKeySecret | quote }}
